### ISSUE TITLE
cannot use with HotModuleReplacementPlugin

### ISSUE THREAD

**Issue by q757571446** [weexteam/weex-vue-precompiler#1]
if i use HotModuleReplacementPlugin, it will occurs ``Property or method "_px2rem" is not defined on the instance but referenced during render.`` 
_vm is undifined

![2017-12-17 10 31 01](https://user-images.githubusercontent.com/13860006/34080502-0d5d60d4-e37a-11e7-88d9-883f0b6f9f97.png)

**Comment by q757571446** [comment]
if i use HotModuleReplacementPlugin, _vm is VueComponent(has not method $processStyle), if i remove HotModuleReplacementPlugin, _vm is Vue。

**Comment by MrRaindrop** [comment]
I'm not sure how is it causing the error, can you provide a example ? A github repo would be good.
